In [2]:
# %pip install scikit-learn

# **Machine Learning in Python: Performing Principal Component Analysis (PCA)**

Dr. Osita Onyejekwe


In this Jupyter notebook, we will be performing Principal Component Analysis (PCA) using the Iris data set as an example.

PCA is an unsupervised learning approach that compresses data from HD to LD

## **1. Iris data set**

### Load library

In [3]:
from sklearn import datasets

### Load dataset

In [4]:
iris = datasets.load_iris()

### Input features

In [5]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

### Output features

In [6]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']

### Assigning Input (X) and Output (Y) variables
Let's assign the 4 input variables to X and the output variable (class label) to Y

In [7]:
X = iris.data
Y = iris.target

### Let's examine the data dimension

In [8]:
X.shape  # 150 rows and 4 columns

(150, 4)

In [9]:
Y.shape  # 150 rows. There are 150 flowers in the data set

(150,)

---

## **2. PCA analysis**

### 2.1. Load library

In [10]:
from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition #PCA
import pandas as pd # pandas

### 2.2. Data scaling

In [11]:
X = scale(X)

### 2.3. Perform PCA analysis

Here we define the number of PC to use as 3

In [12]:
pca = decomposition.PCA(n_components=3)
pca.fit(X)   # the arugment is the input data, which is essentially the x-variable. Notice here that we are using 

# just the x-variable because PCA is an unsupervised learning approach, it does not need the y-variable or the class label 
# in order to learn. 

# it will cluster the data based on the similarities and differences i.e, the eigenvalues that are inherently present 
# in the data set.

PCA(n_components=3)

#### 2.4. Compute and retrieve the **scores** values

In [13]:
scores = pca.transform(X) # the W matrix we derived in class or X^TX and doing the eigendecomposition

In [14]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2', 'PC3'])
scores_df

          PC1       PC2       PC3
0   -2.264703  0.480027  0.127706
1   -2.080961 -0.674134  0.234609
2   -2.364229 -0.341908 -0.044201
3   -2.299384 -0.597395 -0.091290
4   -2.389842  0.646835 -0.015738
..        ...       ...       ...
145  1.870503  0.386966 -0.256274
146  1.564580 -0.896687  0.026371
147  1.521170  0.269069 -0.180178
148  1.372788  1.011254 -0.933395
149  0.960656 -0.024332 -0.528249

[150 rows x 3 columns]

In [15]:
# As a reminder, you can call the data frame variables like this,

scores_df['PC1']

0     -2.264703
1     -2.080961
2     -2.364229
3     -2.299384
4     -2.389842
         ...
145    1.870503
146    1.564580
147    1.521170
148    1.372788
149    0.960656
Name: PC1, Length: 150, dtype: float64

In [16]:
# Add the class label into the data frame 

# note that 'Elif' stands for 'else if' and is used in Python 
# programming to test multiple conditions. It is written following an if statement in Python 
# to check an alternative condition if the first condition is false. 
# The code block under the elif statement will be executed only if its condition is true

Y_label = []

for i in Y:
  if i == 0:
    Y_label.append('Setosa')
  elif i == 1:
    Y_label.append('Versicolor')
  else:
    Y_label.append('Virginica')

Species = pd.DataFrame(Y_label, columns=['Species'])

In [17]:
df_scores = pd.concat([scores_df, Species], axis=1)  # combine dataframe of scores and species together 
df_scores  # extra column called species

          PC1       PC2       PC3    Species
0   -2.264703  0.480027  0.127706     Setosa
1   -2.080961 -0.674134  0.234609     Setosa
2   -2.364229 -0.341908 -0.044201     Setosa
3   -2.299384 -0.597395 -0.091290     Setosa
4   -2.389842  0.646835 -0.015738     Setosa
..        ...       ...       ...        ...
145  1.870503  0.386966 -0.256274  Virginica
146  1.564580 -0.896687  0.026371  Virginica
147  1.521170  0.269069 -0.180178  Virginica
148  1.372788  1.011254 -0.933395  Virginica
149  0.960656 -0.024332 -0.528249  Virginica

[150 rows x 4 columns]

#### 2.5. Retrieve the **loadings** values

In [18]:
# The loadings value (eigendecomposition) tells about the descriptor and the scores values tells us about the data samples

# Because there are 150 flowers, there will be 150 values of scores. (remember, different way of looking at the data)
# Because there are 4 descriptors there will be 4 loadings values (one for each descriptor)

loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2','PC3'], index=iris.feature_names)
df_loadings

                        PC1       PC2       PC3
sepal length (cm)  0.521066  0.377418  0.719566
sepal width (cm)  -0.269347  0.923296 -0.244382
petal length (cm)  0.580413  0.024492 -0.142126
petal width (cm)   0.564857  0.066942 -0.634273

#### 2.6. **Explained variance** for each PC

In [19]:
# the explained variance will tell us what the contribution is to the explained variance of the entire model contributed 
# by each of the principle components. PC1, PC2, PC3 contribute to the overall variance of the data set. 

explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.72962445, 0.22850762, 0.03668922])

## **3. Scree Plot**

### 3.1. Import library

In [20]:
import numpy as np
import plotly.express as px

### 3.2. Preparing explained variance and cumulative variance

#### 3.2.1. Preparing the explained variance data

In [21]:
explained_variance

array([0.72962445, 0.22850762, 0.03668922])

In [22]:
explained_variance = np.insert(explained_variance, 0, 0)

# add origin value at 0,0, which means x and y we will have at zero because in the subsequent lines of code we will
# create the scree plot and manaully make it start from zero since it does not start at the origin

#### 3.2.2. Preparing the cumulative variance data

In [23]:
# at each point of graph cumulative variance of PC1, then PC1+PC2 then PC1 + PC2 + PC3 and including the origin we will have
# 4 data points 

cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

#### 3.2.3. Combining the dataframe

In [24]:
pc_df = pd.DataFrame(['','PC1', 'PC2', 'PC3'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [25]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

    PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.729624                0.730
2  PC2            0.228508                0.959
3  PC3            0.036689                0.996

#### 3.2.4. Making the scree plot

##### 3.2.4.1. Explained Variance

In [26]:
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, 
             x='PC', y='Explained Variance',
             text='Explained Variance',
             width=800)

fig.update_traces(texttemplate='%{text:.3f}', textposition='outside')  # limite to only 3 digit decimal and text outside bar
fig.show()

##### 3.2.4.2. Explained Variance + Cumulative Variance

In [27]:
# https://plotly.com/python/creating-and-updating-figures/

import plotly.graph_objects as go  # normal plotly package 

# first component scatter plot 
# second component bar chart 

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color="LightSeaGreen")
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color="RoyalBlue")
    ))

fig.show()

##### 3.2.4.3. Explained Variance + Cumulative Variance (Separate Plot)

In [28]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color="LightSeaGreen")
    ), row=1, col=1 # scatter plot 
    )

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color="RoyalBlue"),
    ), row=1, col=2  # bar chart
    )

fig.show()

## **4. Scores Plot**

Source: https://plotly.com/python/3d-scatter-plots/

### 4.1. Load library
[API Documentation](https://plotly.com/python-api-reference/plotly.express.html) for *plotly.express* package

In [29]:
import plotly.express as px

### 4.2. Basic 3D Scatter Plot

In [30]:
fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3',
              color='Species')  # data point colored by the flowers species. 

fig.show()

# hover your mouse over the data set you will see which flowers species it belongs to. 

# we can see that the setosa is rather seperated from the versicolor and the virginica 
# versicolor and virginica are quite similar because they share similar space in which some of the data sets are over-lapping
# There def could be false positive in a constructed confusion matrix (after classification) in that a flower that is actually virginica could
# in predicted to be versicolor and vise versa

### 4.3. Customized 3D Scatter Plot

In [31]:
# assign diff symbols to diff flower species 


fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3',
              color='Species',
              symbol='Species',
              opacity=0.5)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))

# https://plotly.com/python/templates/

#fig.update_layout(template='ggplot2') # "plotly", "plotly_white", "plotly_dark", "ggplot2", "seaborn", "simple_white", "none"

## **5. Loadings Plot**

In [32]:
# 3 principle components
# 4 descipots , i.e. 4 loadings values
# we now see the distribution of the descripots 

# sepal width is apparently more important for the setosa flower the reamining 3 are important for setosa and virginica 

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter_3d(df_loadings, x='PC1', y='PC2', z='PC3',
                    text = loadings_label)

fig.show()

---